apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: rag1-may7-2
  janus-idp.io/tekton: rag1-may7-2
  backstage.io/kubernetes-id: rag1-may7-2
  backstage.io/kubernetes-namespace: rag1-may7-2
  app.kubernetes.io/part-of: rag1-may7-2
resources:
  - application-dev.yaml