apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag1-may7-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag1-may7-2:333157e9ba405e5c62df4ec3d3748ed79516f794@sha256:17bf7870ae7b1ae94c4490f9fc9c101c1e732540d9da3bbe61bf16456536361a # use pre-built to bootstrap
          name: app-inference
